### ISSUE TITLE
vm.runInNewContext and friends return the last completion value

### ISSUE THREAD

**Issue by isiahmeadows** [hacksparrow/safe-eval#3]
This would make the module as simple as this:

```js
var vm = require('vm')

module.exports = function safeEval (code, context, opts) {
  var sandbox = {}
  Object.keys(context || {}).forEach(function (key) {
    sandbox[key] = context[key]
  })
  return vm.runInNewContext(code, sandbox, opts)
}
```

**Comment by hacksparrow** [comment]
@isiahmeadows a PR would be much appreciated.

**Comment by isiahmeadows** [comment]
I'm not sure it's necessary, because as of Node 4, you could pretty much do
`module.exports = vm.runInNewContext` directly. Before the new `vm` API
(before Contextify was moved to core), this actually was very useful as a
boilerplate module.

**Comment by hacksparrow** [comment]
Keeping as is for backwards-compatibility.
