### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by loreanvictor** [hacksparrow/safe-eval#6]
there is a performance issue for this function, which stems from node's (vm package) performance issue in context creation. you could of course just wait for nodejs guys to fix it over there, but for now it stopped me from using this package so thought of giving you a heads up. I ended up using a similar code which also can reuse script and context objects.

**Comment by hacksparrow** [comment]
Fixed in latest versions - https://github.com/nodejs/node/issues/14229.
